(global-set-key "\C-cedu"  	(lambda() (interactive) (find-file "c:/Users/vrao/Desktop/vj/class/")))
(global-set-key "\C-cemacs"  	(lambda() (interactive) (find-file "~/.emacs")))
(global-set-key "\C-czs"  	(lambda() (interactive) (find-file "~/.zshrc")))
(global-set-key "\C-cscm"  	(lambda() (interactive) (run-scheme scheme-program-name)))
(global-set-key "\C-cmydb"  	(lambda() (interactive) (find-file "~/.emacs.d/mydb.el")))
(global-set-key "\C-cmyloc"  	(lambda() (interactive) (find-file "~/.emacs.d/mylocation.el")))
(global-set-key "\C-cmyabbrev"  (lambda() (interactive) (find-file "~/.emacs.d/myabbrev.el"))) 
(global-set-key "\C-cmykb"	(lambda() (interactive) (find-file "~/.emacs.d/mykb.el"))) 

(global-set-key "\C-cgdrive"  	(lambda() (interactive) (find-file "g:/")))
(global-set-key "\C-cdt"  	(lambda() (interactive) (find-file "c:/Users/vrao/Desktop/")))
(global-set-key "\C-cses"  	(lambda() (interactive) (find-file "c:/eras/db-sessions/")))
(global-set-key "\C-cvw" 	'write-region)
(global-set-key "\C-crevert" 	'revert-buffer)
(global-set-key "\C-csh" 	'shell)
(global-set-key "\C-cren" 	'rename-buffer)
(global-set-key "\C-cmv" 	'rename-uniquely)
(global-set-key "\C-cfoc" 	'focus-line)
(global-set-key "\C-cps" 	'ps-print-buffer)
(global-set-key "\C-cpr" 	'ps-print-region)
(global-set-key "\C-ckp" 	'kill-paragraph)
(global-set-key "\C-ckl" 	'my-kill-line)
(global-set-key "\C-cora"  	(lambda() (interactive) (find-file "c:/oracle/product/11.2.0/client_1/network/admin")))
(global-set-key "\C-ctop"  	(lambda() (interactive) (find-file "C:/cvswork/mcat_reg/dbtops")))
(global-set-key "\C-l" 		'my-kill-line)
(global-set-key "\C-ch" 	'go-home)
(global-set-key "\C-csch" 	(lambda() (interactive)  (switch-to-buffer "*scheme*")))
(global-set-key "\C-ccolor"  	'mysetcolor)
(global-set-key "\C-ctoo"  	'tool-bar-mode)
(global-set-key "\C-cssh"  	(lambda() (interactive) (find-file "~/.ssh/id_rsa.pub")))

(global-set-key "\C-z" 		'undo)
(global-set-key "\C-cvv" 	'clipboard-yank)
(global-set-key "\C-cvx" 	'clipboard-kill-region)
(global-set-key "\C-cgoto" 	'goto-line)
(global-set-key "\C-cvw" 	'write-region)
(global-set-key "\C-cren" 	'rename-buffer)
(global-set-key "\C-cps" 	'ps-print-buffer)
(global-set-key "\C-ckw" 	'tim-kill-word)
(global-set-key "\C-ckb" 	'tim-backward-kill-word)
(global-set-key "\C-ckp" 	'kill-paragraph)
(global-set-key "\C-ckl" 	'my-kill-line)
(global-set-key "\C-ck+"        'text-scale-increase)
 
(global-set-key "\C-cwhi" 	'delete-trailing-whitespace)
(global-set-key "\C-cesh" 	'eshell)
;(global-set-key "\C-cvj"  	(lambda() (interactive) (write-file get_temp_buff))))
;(global-set-key "\C-cvj"  	(lambda() (interactive) (write-file(get_temp_buff) t)))
(global-set-key "\C-csvt"  	(lambda() (interactive) (save-tmp-buff)))
(global-set-key "\C-csvq"  	(lambda() (interactive) (save-sql-session)))
(global-set-key "\C-ctmp"  	(lambda() (interactive) (switch-to-buffer (make-tmp-name))))
 
(global-set-key [(C tab)]  	'other-window)
(global-set-key [M-down] 	'scroll-other-window-down)
(global-set-key [apps] 		'myexpand-abbrev)
(global-set-key [C-rwindow] 	'dired )
(global-set-key [M-rwindow] 	'dired )
(global-set-key [f1]  		'delete-other-windows)
(global-set-key [f10] 		'delete-window)
(global-set-key [f11] 		'delete-frame)
(global-set-key [f12] 		'make-frame-command)
(global-set-key [C-f11] 	(lambda() (interactive) 
				  (info "eintr") ))
 
(global-set-key [f2] 		'split-window-vertically)
(global-set-key [C-f2] 		'rename-buffer)
(global-set-key [f3] 		'find-file)
(global-set-key [C-f5] 		'my-dired-exec)
(global-set-key [f7] 		'goto-line)
(global-set-key [f8] 		'toggle-truncate-lines)
(global-set-key [f9] 		'my-kill-line)
(global-set-key [f4] 		'kill-buffer)
(global-set-key [C-lwindow] 	'switch-to-buffer)
(global-set-key [M-lwindow] 	'my-list-buffers)
(global-set-key [pause] 	'keyboard-quit)
(global-set-key [C-kp-insert] 	'dup-this-line)
(global-set-key [C-kp-0] 	'dup-this-line)
(global-set-key [M-kp-insert] 	'my-kill-line)
(global-set-key [M-kp-0] 	'my-kill-line)
(global-set-key [C-return] 	'newline-and-indent)
(global-set-key [M-f10] 	'my-exec-shell-in-buffer)
(global-set-key [C-f10] 	'my-clear-scratch)
(global-set-key [C-f9] 		'my-comint-output-edit)
(global-set-key [M-f9] 		'my-comint-output-append)
(global-set-key [C-prior] 	'isearch-backward)
(global-set-key [C-next] 	'isearch-forward)
(global-set-key "\C-\\" 	'comint-replace-by-expanded-filename)
(global-set-key "\C-v" 		'yank)
(global-set-key "\C-b" 		'yank-pop)

(global-set-key [(C tab)]  	'other-window)
(global-set-key [M-down] 	'scroll-other-window-down)
(global-set-key [apps] 		'myexpand-abbrev)
(global-set-key [C-apps] 	'switch-to-buffer)
(global-set-key [C-rwindow] 	'dired )
(global-set-key [M-rwindow] 	'dired )
(global-set-key [f1]  		'delete-other-windows)
(global-set-key [f10] 		'delete-window)
(global-set-key [f11] 		'delete-frame)
(global-set-key [f12] 		'make-frame-command)
(global-set-key [f2]  		'split-window-vertically)
(global-set-key [f3]  		'find-file)

(global-set-key [C-f5] 		'my-dired-exec)
(global-set-key [f6] 		'my-jde-run)
(global-set-key [C-f6] 		'my-jde-run-args)
(global-set-key [f7] 		'goto-line)
(global-set-key [f8] 		'toggle-truncate-lines)
;(global-set-key [f9] 		'(switch-to-buffer '*scratch*))
(global-set-key [f4] 		'kill-this-buffer)
(global-set-key [M-lwindow]	'switch-to-buffer)
(global-set-key [C-lwindow]	'list-buffers)
(global-set-key [pause] 	'keyboard-quit)
(global-set-key [C-kp-insert] 	'dup-this-line)
(global-set-key [C-kp-0] 	'dup-this-line)
(global-set-key [M-kp-insert] 	'my-kill-line)
(global-set-key [M-kp-0] 	'my-kill-line)
(global-set-key [C-return] 	'newline-and-indent)
(global-set-key "\C-ccase" 	'toggle-case-fold-search)

(global-set-key "\C-creg" 	'search-forward-regexp)

(global-set-key "\C-c-"	      
		(lambda()  (interactive) (text-scale-decrease 1)))
(global-set-key "\C-c+"	      
		(lambda()  (interactive) (text-scale-increase 1)))

;(global-set-key [C-M-s]  're-search-forward)
		
